# Generated by Django 5.0.3 on 2024-03-15 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ad Title')),
                ('description', models.TextField(max_length=2000, verbose_name='Ad Descriptin')),
                ('keywords', models.CharField(max_length=255, verbose_name='Keywords')),
                ('link', models.URLField(verbose_name='Ad Link')),
                ('advertiser_name', models.CharField(max_length=100, verbose_name='Name/Company')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Id')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Whatsapp Number')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.TextField(max_length=500, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/ad_cover/', verbose_name='Ad image')),
                ('ad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='ads.adimage'),
        ),
    ]
