# Generated by Django 5.0.3 on 2024-03-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_active_ad_datetime_created_ad_datetime_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date time Created'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
